version: "2"
services:
  web:
    image: webdevops/php-nginx
#    container_name: contao-nginx
    ports:
      - "8088:80"
    depends_on:
      - "mysql"
    links:
      - mysql
    volumes:
      - ./contao:/app
    environment:
      WEB_DOCUMENT_INDEX: "/web/app.php"
  mysql:
    image: mysql:latest
#    container_name: contao-mysql
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contaodb
      
      
