sudo: required

language: ruby

services:
- docker

   
before_install:  
- "echo  'ready?'"
#- docker build -t robidock/myrunning .
- docker pull robidock/myrunning
- docker run --name testus  robidock/myrunning
- docker ps -a
- docker images
#- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.example.com



script:
- docker images robidock/myrunning

after_success:
- "echo 'ready?'"
- if [ "$TRAVIS_BRANCH" == "master" ]; then
     docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
   docker push robidock/myrunning;
   fi

before_deploy: "echo 'ready?'"

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
            
        
