language: python
python:
  - 2.7

services:
  - docker
  

install:
  - docker build -t blog .
  - docker run -d -p 127.0.0.1:80:80 --name blog blog
  - docker-compose -f mybsp/docker-compose.yml up  -d

before_script:
  - pip install -r requirements.txt
  - pip install mock
  - pip install requests
  - pip install feedparser

script:
  - docker ps 
  - python tests.py
