# mybsp
version: "2"
services:
  nginx:
    image: prooph/nginx:www
    ports:
      - "8081:80"
      - "443:443"
    links:
      - php:php
    volumes_from:
      - dataphp

  php:
    image: prooph/php:7.0-fpm
    links:
      - mariadb:mariadb
    volumes_from:
      - dataphp

  dataphp:
    image: debian:jessie
    volumes:
      - ./public:/var/www/public


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    #container_name: phpmyadmin
    environment:
       - PMA_ARBITRARY=1
    restart: always
    links:
      - mariadb:mariadb
    ports:
       - 8082:80
    volumes_from:
       - dataphpmyadmin
     
  dataphpmyadmin:
    image: debian:jessie
    volumes:
       - /sessions
       - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  mariadb:
    image: mariadb
 #   ports:
 #     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=prooph
    
    volumes_from:
       - datamariadb  
  
  datamariadb:
    image: debian:jessie
    volumes:
       - ./dbdata:/var/lib/mysql
       


      
                   
