version: "2"
services:
  webserver:
    image: nginx:1.11
    ports:
      - "8080:80"
    volumes:
      - "./etc/nginx:/etc/nginx/conf.d"   #default.conf
      - "./src:/var/www"                
  php:
    image: servivum/php:7.0-fpm
    volumes:        
      - "./etc/php/fpm:/usr/local/etc"   # php-fpm.conf
      - "./etc/php:/usr/local/etc/php"   # php.ini
      - "./src:/var/www/"

  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db

      
      